version: '3.4'

services:
  ecommerce.api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    build:
      context: .
      dockerfile: Ecommerce.API/Dockerfile
    ports:
        - "8080:5227"  # Mapear el puerto 5227 del contenedor al puerto 8080 del host para HTTP
        - "8081:7295"  # Mapear el puerto 7295 del contenedor al puerto 8081 del host para HTTPS- 