version: '3.4'

services:
  ecommerce.api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    build:
      context: .
      dockerfile: Ecommerce.API/Dockerfile
#    ports:
#      - "8080:7295"  # Mapear el puerto 80 del contenedor al puerto 8080 del host