version: '3.4'

services:
  ecommerce.api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    build:
      context: .
      dockerfile: Ecommerce.API/Dockerfile
    ports:
      - 5227:5227
      - 7295:7295

  ecommerce.webassembly:
    image: ${DOCKER_REGISTRY-}ecommercewebassembly
    build:
      context: .
      dockerfile: Ecommerce.WebAssembly/Dockerfile
    ports:
      - 7186:7186
      - 5167:5167
  