version: '3.8'

services:
  ecommerce-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - ecommerce-webassembly

  ecommerce-webassembly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
